<?php
/**
 * 面板widget
 * 前端调用：\zyblog\dwz\widget\DwzPanel::widget(["title" =>"","content"=>""]);
 * User: zhangyue
 * http://www.zyblog.net
 * Date: 2016/8/8
 * Time: 20:39
 */

namespace zyblog\dwz\widget;


use yii\base\Widget;

class DwzPanel extends Widget
{
    //标题
    public $title;
    //内容
    public $content;
    //默认内容区高度
    public $height=300;
    //初始状态是否是关闭状态，默认false是打开状态
    public $close=false;
    //是否可折叠，默认是true是可折叠
    public $collapse=true;


    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $class='panel';
        if ($this->close)
            $class.=' close';
        if ($this->collapse)
            $class.=' collapse';

        if($this->height!==null && is_numeric($this->height)){
            $defH = "defH='{$this->height}'";
        }

        $html = "<div class='$class' $defH>";
        $html .=  "<h1>{$this->title}</h1>";
        $html .=  "<div>{$this->content}</div>";
        $html .= "</div>";

        echo $html;

    }

}